_wandb:
    value:
        cli_version: 0.21.0
        e:
            5c06du15n6qfzqqvqd316vno39tlsza4:
                codePath: plots/PLOTS.ipynb
                codePathLocal: PLOTS.ipynb
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "982820896768"
                        used: "375402377216"
                email: kallel@eurecom.fr
                executable: /home/mahdi/Desktop/supersac/.venv_jax/bin/python
                git:
                    commit: 8f3bff1da718025d199dfadf818ccd7d920ebcf6
                    remote: https://github.com/kallel-mahdi/supersac
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-69f55b9a-f421-76d7-a34a-cb190f1ff202
                host: mahdi-X670E-Pro-RS
                memory:
                    total: "66484998144"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.35
                program: /home/mahdi/Desktop/supersac/plots/PLOTS.ipynb
                python: CPython 3.12.0
                root: /home/mahdi/Desktop/supersac/plots
                startedAt: "2025-08-01T12:05:54.278881Z"
                writerId: 5c06du15n6qfzqqvqd316vno39tlsza4
        m: []
        python_version: 3.12.0
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.0
            "5": 0.21.0
            "8":
                - 1
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
activation_fn:
    value: tanh
algo_name:
    value: superppo
bound_actions:
    value: true
buffer_size:
    value: 50000
clipping_ratio:
    value: 0.25
entropy_coeff:
    value: 0.5
env_name:
    value: Hopper-v5
evaluate_grad:
    value: true
exp_descriptor:
    value: null
exp_prefix:
    value: null
experiment_id:
    value: null
gae_lambda:
    value: 0.5
gamma:
    value: 0.99
hidden_dims:
    value: 256
intertwine_updates:
    value: true
max_steps:
    value: 1000000
min_target:
    value: false
num_critic_updates:
    value: 5000
num_critics:
    value: 2
num_epochs:
    value: 10
on_policy_data:
    value: false
policy_steps:
    value: 5000
project_name:
    value: AAAI_ABLATIONS_INTER
seed:
    value: 121958
spo_loss:
    value: false
stable_scheme:
    value: true
temperature:
    value: 1
use_layer_norm:
    value: true
